
services:
  db:
    image: mysql:8.0
    container_name: ip-scanner-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

#  app:
#    build: .
#    container_name: ip-scanner-backend
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    environment:
#      DB_DRIVER: ${DB_DRIVER}
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#      DB_NAME: ${DB_NAME}
#      DB_MAX_IDLE_CONNS: ${DB_MAX_IDLE_CONNS}
#      DB_MAX_OPEN_CONNS: ${DB_MAX_OPEN_CONNS}
#      DB_CONN_MAX_LIFETIME: ${DB_CONN_MAX_LIFETIME}
#    command: go run main.go

volumes:
  db_data:
